---
apiVersion: v1
kind: Namespace
metadata:
  name: mbici-pr
  labels:
    name: mbici-pr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mbici-cache-pr
  labels:
    name: mbici-cache-pr
spec:
  capacity:
    storage: 4Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.2
    - fsc
  nfs:
    path: /srv/mbi-cache
    server: 172.22.13.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mbici-cache
  namespace: mbici-pr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      name: mbici-cache-pr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mbici-result-pr
  labels:
    name: mbici-result-pr
spec:
  capacity:
    storage: 28Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.2
    - fsc
  nfs:
    path: /srv/mbi-result/pr
    server: 172.22.13.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mbici-result
  namespace: mbici-pr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 28Gi
  selector:
    matchLabels:
      name: mbici-result-pr
